# Generated by Django 4.1.4 on 2022-12-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobstler_main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="advertisement", name="active_until",),
        migrations.RemoveField(model_name="advertisement", name="image",),
        migrations.AddField(
            model_name="advertisement",
            name="image_url",
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="jobstler_main.useraccount",
            ),
        ),
    ]
