# Generated by Django 4.1.4 on 2022-12-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobstler_main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="advertisement", name="user_account_fk",),
        migrations.RemoveField(model_name="comment", name="user_account_fk",),
    ]
