# Generated by Django 4.1.4 on 2022-12-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobstler_main", "0002_remove_advertisement_active_until_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
