# Generated by Django 4.1.4 on 2022-12-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobstler_main", "0003_alter_advertisement_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="privatemessagetable", name="message",),
        migrations.RemoveField(model_name="privatemessagetable", name="recipient",),
        migrations.RemoveField(model_name="privatemessagetable", name="sender",),
        migrations.DeleteModel(name="Message",),
        migrations.DeleteModel(name="PrivateMessageTable",),
    ]
