# Generated by Django 4.1.4 on 2022-12-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="date_of_birth",),
    ]
